2023-04-11 21:36:41,656 ERROR: Exception on /user/susan [GET] [in C:\Users\xyz\Desktop\microblog\env\lib\site-packages\flask\app.py: 1744]
Traceback (most recent call last):
  File "C:\Users\xyz\Desktop\microblog\env\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\xyz\Desktop\microblog\env\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\xyz\Desktop\microblog\env\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\xyz\Desktop\microblog\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\xyz\Desktop\microblog\env\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\xyz\Desktop\microblog\app\routes.py", line 74, in user
    return render_template('user.html', user = user, posts = posts, form=form)
  File "C:\Users\xyz\Desktop\microblog\env\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "C:\Users\xyz\Desktop\microblog\env\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "C:\Users\xyz\Desktop\microblog\env\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\xyz\Desktop\microblog\env\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\xyz\Desktop\microblog\app\templates\user.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "C:\Users\xyz\Desktop\microblog\app\templates\base.html", line 33, in top-level template code
    {% block content %} {% endblock %}
  File "C:\Users\xyz\Desktop\microblog\app\templates\user.html", line 11, in block 'content'
    <p>{{ user.followers.count }} followers, {{ user.followed.count }} following</p>
  File "C:\Users\xyz\Desktop\microblog\env\lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.models.User object' has no attribute 'followes'
2023-04-11 21:36:44,353 ERROR: Exception on /user/susan [GET] [in C:\Users\xyz\Desktop\microblog\env\lib\site-packages\flask\app.py: 1744]
Traceback (most recent call last):
  File "C:\Users\xyz\Desktop\microblog\env\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\xyz\Desktop\microblog\env\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\xyz\Desktop\microblog\env\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\xyz\Desktop\microblog\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\xyz\Desktop\microblog\env\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\xyz\Desktop\microblog\app\routes.py", line 74, in user
    return render_template('user.html', user = user, posts = posts, form=form)
  File "C:\Users\xyz\Desktop\microblog\env\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "C:\Users\xyz\Desktop\microblog\env\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "C:\Users\xyz\Desktop\microblog\env\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\xyz\Desktop\microblog\env\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\xyz\Desktop\microblog\app\templates\user.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "C:\Users\xyz\Desktop\microblog\app\templates\base.html", line 33, in top-level template code
    {% block content %} {% endblock %}
  File "C:\Users\xyz\Desktop\microblog\app\templates\user.html", line 11, in block 'content'
    <p>{{ user.followers.count }} followers, {{ user.followed.count }} following</p>
  File "C:\Users\xyz\Desktop\microblog\env\lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.models.User object' has no attribute 'followes'
2023-04-11 21:36:55,596 INFO: Microblog startup [in C:\Users\xyz\Desktop\microblog\app\__init__.py: 42]
2023-04-11 21:37:22,270 INFO: Microblog startup [in C:\Users\xyz\Desktop\microblog\app\__init__.py: 42]
